<div class="ui-grid-a">
    <div class="title">
        <h1>Ficha Técnica - Geral</h1>
        <a onclick="" class="btn-azul pull-right btn-save" style="margin-right: 120px;"><span class="icon-ok-3"></span>imprimir gráfica</a>
        <a onclick="" class="btn-azul pull-right btn-save" style="margin-right: 323px;"><span class="icon-ok-3"></span>imprimir site</a>
        <a onclick="savedata();" class="btn-azul pull-right btn-save"><span class="icon-ok-3"></span>salvar</a>
    </div>
    <div id="answer" class="resposta">
        <div class="alert" role="alert"></div>
    </div>
    <div class="content">
        
        <form id="frm_ft" method="post">
            <div class="ui-grid-a cont-form">
                <div class="holderimgs">
                    <div class="grid-fotoprincipal">
                        <label for="foto-principal" class="label-line">Foto Principal: <span>Formato 2197px X 1162px (300dpi)</span></label>
                        <img id="foto-principal" onclick="activenext('imgfotoprincipal');" src="<?= $this->foto; ?>" />
                        <input type="file" name="imgfotoprincipal" id="imgfotoprincipal" accept="image/*" onchange="getbase64('foto-principal');" />
                    </div>
                    <div class="grid-vinheta">
                        <label for="vinheta" class="label-line">Vinheta: <span>Formato 829px X 879px (300dpi)</span></label>
                        <img id="vinheta" onclick="activenext('imgvinheta');" src="<?= $this->vinheta; ?>" />
                        <input type="file" name="imgvinheta" id="imgvinheta" accept="image/*" onchange="getbase64('vinheta');" />
                    </div>
                </div>
                <div class="traco"></div>
                    <label for="complemento" class="label-line">Complemento:</label>
                    <input type="text" name="complemento_modelo" id="complemento" value="<?= (isset($this->content[0]['complemento_modelo'])) ? $this->content[0]['complemento_modelo'] : ''; ?>" data-mini="true">
                <div class="traco"></div>

                    <label for="tracao" class="label-line">Tração:</label>
                    <input type="text" name="tracao" id="tracao" value="<?= (isset($this->content[0]['tracao'])) ? $this->content[0]['tracao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="classificacao" class="label-line">Classificação:</label>
                    <input type="text" name="classificacao" id="classificacao" value="<?= (isset($this->content[0]['classificacao'])) ? $this->content[0]['classificacao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="aplicacao" class="label-line">Aplicação:</label>
                    <input type="text" name="aplicacao" id="aplicacao" value="<?= (isset($this->content[0]['aplicacao'])) ? $this->content[0]['aplicacao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="b09" class="label-line">B09:</label>
                    <input type="text" name="b09" id="b09" value="<?= (isset($this->content[0]['b09'])) ? $this->content[0]['b09'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="datadepublicacao" class="label-line">Data de publicação:</label>
                    <input type="text" name="data_da_publicacao" id="datepicker" value="<?= $this->content[0]['data_publicacao_dados']; ?>" data-mini="true">
                    <input type="hidden" name="modelo" id="modelo" value="" />
            </div>
        </form>
    </div><!-- /content -->

</div><!-- ui-grid-a -->


<script id="panel-init">
$(document).on('pagehide', 'div', function (event, ui) { 
    var page = jQuery(event.target);
    if (page.attr('data-cache') == 'never') { 
        page.remove(); 
    }; 
});
$( "#datepicker" ).datepicker({
    dateFormat: 'dd/mm/yy',
    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    nextText: 'Próximo',
    prevText: 'Anterior'
});
$('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
$('#mnulateralesquerdo').children('div:first').children('ul').children('li:first').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");

function activenext(obj){
    var id = '#' + obj;
    $(id).trigger('click');
}
function getbase64(id){
    var reader = new FileReader();
    reader.onload = function(e){
        document.getElementById(id).src = e.target.result;
    };
    reader.readAsDataURL(event.target.files[0]);
}
function savedata(){
    $.mobile.loading("show");
    visao  = $('#imgfotoprincipal').attr('data-visao');
    modelo = $('#meumodelo option:selected').text();
    modelo = modelo.replace(/ /g,'').replace(/\//g,'_').toLowerCase();
    nomeim = [modelo,visao,'pic_1.jpg'];
    filename = nomeim.join("");

    var frm  = document.getElementById('imgfotoprincipal');
    var arq  = frm.files[0];
    var info = new FormData();
    info.append('arquivo',arq);
    info.append('nomefile',filename);
    $.ajax({
        url: '/modelos/fichatecnica/uploadimg',
        type: 'POST',
        data: info,
        cache: false,
        processData: false,
        contentType: false
    }).done(function(data){
        console.log(data);
        $.mobile.loading("hide");
    }).fail(function(anw){
        console.log('falhou')
    });

    /*$.mobile.loading("show");
    if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
        $('#answer').slideUp('fast');
        $('#answer').children('div').removeClass('alert-danger');
        $('#answer').children('div').removeClass('alert-success');
    }
    var a = $('#complemento').val();
    var b = $('#tracao').val();
    var c = $('#classificacao').val();
    var d = $('#aplicacao').val();
    var e = $('#b09').val();
    var f = $('#datepicker').val();
    //console.log('Antes ' + a + ' | ' + b + ' | ' + c + ' | ' + d + ' | ' + e + ' | ' + f);
    $.post('/modelos/actions/savegeral',{complemento : a, tracao : b,classificacao : c,aplicacao: d,b09: e,data_da_publicacao: f})
    .done(function(data){
        console.log(data);
        var result = JSON.parse(data);
        $.mobile.loading("hide");
        $('#answer').children('div').addClass('alert-success').html(result[0].msg_retorno);
        $('#answer').slideDown().delay(5000).slideUp();
    })
    .fail(function(err){
        var result = JSON.parse(err);
        $.mobile.loading("hide");
        $('#answer').children('div').addClass('alert-danger').html(result[0].msg_retorno);
        $('#answer').delay(5000).slideDown();
    });*/
}        
</script>
