<div class="ui-grid-a">
    <div class="title">
        <h1>Ficha Técnica - Geral</h1>
        <a onclick="generatepdf('grafica');" class="btn-azul pull-right btn-save" style="margin-right: 120px;"><span class="icon-ok-3"></span>imprimir gráfica</a>
        <a onclick="generatepdf('imprimir');" class="btn-azul pull-right btn-save" style="margin-right: 323px;"><span class="icon-ok-3"></span>imprimir site</a>
        <a onclick="savedata();" class="btn-azul pull-right btn-save"><span class="icon-ok-3"></span>salvar</a>
    </div>
    <div id="answer" class="resposta">
        <div class="alert" role="alert"></div>
    </div>
    <div class="content">
        
        <form id="frm_ft" method="post">
            <div class="ui-grid-a cont-form">
                <div class="holderimgs">
                    <div class="grid-fotoprincipal">
                        <label for="foto-principal" class="label-line">Foto Principal: <span>Formato 2197px X 1162px (300dpi)</span></label>
                        <img id="foto-principal" onclick="activenext('imgfotoprincipal');" src="<?=  $this->foto; ?>" />
                        <input type="file" name="imgfotoprincipal" id="imgfotoprincipal" accept="image/*" onchange="getbase64('foto-principal');" />
                    </div>
                    <div class="grid-vinheta">
                        <label for="vinheta" class="label-line">Vinheta: <span>Formato 829px X 879px (300dpi)</span></label>
                        <img id="vinheta" onclick="activenext('imgvinheta');" src="<?= $this->vinheta; ?>" />
                        <input type="file" name="imgvinheta" id="imgvinheta" accept="image/*" onchange="getbase64('vinheta');" />
                    </div>
                </div>
                <div class="traco"></div>
                    <label for="complemento" class="label-line">Complemento:</label>
                    <input type="text" name="complemento_modelo" id="complemento" value="<?= (isset($this->content[0]['complemento_modelo'])) ? $this->content[0]['complemento_modelo'] : ''; ?>" data-mini="true">
                <div class="traco"></div>

                    <label for="tracao" class="label-line">Tração:</label>
                    <input type="text" name="tracao" id="tracao" value="<?= (isset($this->content[0]['tracao'])) ? $this->content[0]['tracao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="classificacao" class="label-line">Classificação:</label>
                    <input type="text" name="classificacao" id="classificacao" value="<?= (isset($this->content[0]['classificacao'])) ? $this->content[0]['classificacao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="aplicacao" class="label-line">Aplicação:</label>
                    <input type="text" name="aplicacao" id="aplicacao" value="<?= (isset($this->content[0]['aplicacao'])) ? $this->content[0]['aplicacao'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="b09" class="label-line">B09:</label>
                    <input type="text" name="b09" id="b09" value="<?= (isset($this->content[0]['b09'])) ? $this->content[0]['b09'] : ''; ?>" data-mini="true">

                <div class="traco"></div>

                    <label for="datadepublicacao" class="label-line">Data de publicação:</label>
                    <input type="text" name="data_da_publicacao" id="datepicker" value="<?= $this->content[0]['data_publicacao_dados']; ?>" data-mini="true">
                    <input type="hidden" name="modelo" id="modelo" value="" />

                <div class="traco"></div>

                    <label for="nome_arquivo_print" class="label-line">Nome do arquivo impressão:</label>
                    <input type="text" name="nome_arquivo_print" id="nome_arquivo_print" value="<?= (isset($this->content[0]['nome_arquivo_print'])) ? $this->content[0]['nome_arquivo_print'] : ''; ?>" data-mini="true">
 
               <!--  <div class="traco"></div>

                    <label for="comentario_1" class="label-line">Comentário 1:</label>
                    <textarea id="comentario_1" name="comentario_1" class="height-text-area ui-input-text ui-textinput-autogrow" rows="50" cols="90">
                        <?= (isset($this->content[0]['comentario_1'])) ? trim($this->content[0]['comentario_1']) : ''; ?>
                    </textarea>

                <div class="traco"></div>

                    <label for="comentario_2" class="label-line">Comentário 2:</label>
                    <textarea id="comentario_2" name="comentario_2" class="height-text-area ui-input-text ui-textinput-autogrow" rows="50" cols="90">
                        <?= (isset($this->content[0]['comentario_2'])) ? trim($this->content[0]['comentario_2']) : ''; ?>
                    </textarea> -->
            
            </div>
        </form>
    </div><!-- /content -->
<a id="downloadfile" style="visibility: hidden;">&nbsp;</a>
</div><!-- ui-grid-a -->


<script id="panel-init">
//INICIALIZA AS VARIAVEIS PARA VERIFICACAO DO UPLOAD
var img_principal = false; 
var img_vinheta = false;

$(document).on('pagehide', 'div', function (event, ui) { 
    var page = jQuery(event.target);
    if (page.attr('data-cache') == 'never') { 
        page.remove(); 
    }; 
});

$( "#datepicker" ).datepicker({
    dateFormat: 'dd/mm/yy',
    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    nextText: 'Próximo',
    prevText: 'Anterior'
});
$('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
$('#mnulateralesquerdo').children('div:first').children('ul').children('li:first').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");

//VALIDA A DIMENSAO DA IMAGEM
function ativafigura(id) {
    //alert(id);
    if (id == 'foto-principal'){
        var largura = document.getElementById('foto-principal').naturalWidth;
        var altura = document.getElementById('foto-principal').naturalHeight;        
    }else if(id == 'vinheta'){
        var largura = document.getElementById('vinheta').naturalWidth;
        var altura = document.getElementById('vinheta').naturalHeight;          
    }
    //alert(largura+" x "+altura);

    if (largura == 2197 && altura == 1162 && id == 'foto-principal' ){ //FOTO PRINCIPAL
        img_principal = true;
        return true;
    }else if(largura >= 800 && altura >= 800 && id == 'vinheta'){ //VINHETA
    //}else if(largura == 829 && altura == 879 && id == 'vinheta'){ //VINHETA
        img_vinheta = true;
        return true;
    }else if(largura == 512 && altura == 271){ //IMAGEM PADRAO - QUE NÃO FOI ALTERADA
        return false; //PARA NÃO REALIZAR O UPLOAD DA  IMAGEM
    }else{
        //alert("FORMATO DA IMAGEM INVALIDO !");
        $('#answer').children('div').addClass('alert-danger').html('FORMATO DE IMAGEM INVALIDO!');
        $('#answer').slideDown().delay(5000).slideUp();        
        return false;
    }
}

function activenext(obj){
    var id = '#' + obj;
    $(id).trigger('click');
}

function getbase64(id){
    if(ativafigura(id)){
        var reader = new FileReader();
        reader.onload = function(e){
            document.getElementById(id).src = e.target.result;
        };
        reader.readAsDataURL(event.target.files[0]);        
    }

}

function savedata(){
    $.mobile.loading("show");
    
    if((img_principal === true) || (img_vinheta === true)){
        visao  = $('#imgfotoprincipal').attr('data-visao');
        modelo = $('#meumodelo option:selected').text();
        modelo = modelo.replace(/ /g,'_').replace(/_\/_/g,'_').toLowerCase();
        
        nomeft = [modelo,visao,'_pic_1.jpg'];
        nomevi = [modelo,visao,'_pic_2.jpg'];
        filename = nomeft.join("");
        vinheta  = nomevi.join("");
        
        if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
            $('#answer').slideUp('fast');
            $('#answer').children('div').removeClass('alert-danger');
            $('#answer').children('div').removeClass('alert-success');
        }
        $('#answer').children('div').addClass('alert-success').html('Detectamos alteração nas imagens. Iniciando upload!');
        $('#answer').slideDown();
        if((img_principal === true) && (img_vinheta === true)){
            var inputfoto = document.getElementById('imgfotoprincipal');
            var inputvinh = document.getElementById('imgvinheta');
            var foto = inputfoto.files[0];
            var vinh = inputvinh.files[0];
            var frmfoto = new FormData();
            var frmvinh = new FormData();
            frmfoto.append('arquivo',foto);
            frmfoto.append('nomefile', filename);
            frmvinh.append('arquivo',vinh);
            frmvinh.append('nomefile', vinheta);
            $('#answer').children('div').html('Realizando upload da foto principal ...');
            $.ajax({
                url: '/modelos/fichatecnica/uploadimg',
                type: 'POST',
                data: frmfoto,
                cache: false,
                processData: false,
                contentType: false
            }).done(function(data){
                $('#answer').children('div').html('Realizando upload da vinheta ...');
                $.ajax({
                    url: '/modelos/fichatecnica/uploadimg',
                    type: 'POST',
                    data: frmvinh,
                    cache: false,
                    processData: false,
                    contentType: false
                }).done(function(data){
                    $('#answer').children('div').html('Upload realizado com Sucesso');
                    console.log(data);
                    img_principal = false;
                    img_vinheta   = false;
                    gravadata();
                }).fail(function(arg){
                    $.mobile.loading("hide");
                    console.log(arg);
                });
            }).fail(function(msg){
                $.mobile.loading("hide");
                console.log(msg);
            });
        }else{
            var frm  = (img_principal === true) ? document.getElementById('imgfotoprincipal') : document.getElementById('imgvinheta');
            var arq  = frm.files[0];
            var info = new FormData();
            arquivo  = (img_principal === true) ? filename : vinheta;
            info.append('arquivo',arq);
            info.append('nomefile',arquivo);
            $.ajax({
                url: '/modelos/fichatecnica/uploadimg',
                type: 'POST',
                data: info,
                cache: false,
                processData: false,
                contentType: false
            }).done(function(data){
                $('#answer').children('div').html('Gravando dados!');
                console.log(data);
                img_principal = false;
                img_vinheta   = false;
                gravadata();
            }).fail(function(anw){
                $.mobile.loading("hide");
                console.log('falhou');
                $('#answer').children('div').addClass('alert-danger').html('ERRO AO FAZER O UPLOAD DA IMAGEM! TENTE NOVAMENTE');
                $('#answer').slideDown().delay(5000).slideUp();
            });
        }
    }else{
        gravadata();
    }
}  

function gravadata(){
    if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
        $('#answer').slideUp('fast');
        $('#answer').children('div').removeClass('alert-danger');
        $('#answer').children('div').removeClass('alert-success');
    }
    var a = $('#complemento').val();
    var b = $('#tracao').val();
    var c = $('#classificacao').val();
    var d = $('#aplicacao').val();
    var e = $('#b09').val();
    var f = $('#datepicker').val();
    var g = $('#nome_arquivo_print').val();
    //console.log('Antes ' + a + ' | ' + b + ' | ' + c + ' | ' + d + ' | ' + e + ' | ' + f);
    $.post('/modelos/actions/savegeral',{complemento : a, tracao : b,classificacao : c,aplicacao: d,b09: e,data_da_publicacao: f,nome_do_arquivo: g})
    .done(function(data){
        console.log(data);
        var result = JSON.parse(data);
        $.mobile.loading("hide");
        $('#answer').children('div').addClass('alert-success').html(result[0].msg_retorno);
        $('#answer').slideDown().delay(5000).slideUp();
    })
    .fail(function(err){
        var result = JSON.parse(err);
        $.mobile.loading("hide");
        $('#answer').children('div').addClass('alert-danger').html(result[0].msg_retorno);
        $('#answer').delay(5000).slideDown();
    });
}

function generatepdf(tipo){
    $.mobile.loading("show");
    if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
        $('#answer').slideUp('fast');
        $('#answer').children('div').removeClass('alert-danger');
        $('#answer').children('div').removeClass('alert-success');
    }
    $('#answer').children('div').addClass('alert-success');
    $('#answer').children('div').html('Reunindo dados!');
    $('#answer').slideDown();
    $.post('/modelos/pdf/index',{versao: tipo})
    .done(function(data){
        console.log(data);
        var result = JSON.parse(data);
        var nomepdf= result.arquivo;
        if(tipo == 'imprimir'){
            nomepdf = nomepdf + ' Site.pdf';
        }else{
            nomepdf = nomepdf + ' Grafica.pdf';
        }
        $('#answer').children('div').html('Informações obtidas, gerando o pdf...');
        $.post('/modelos/pdf/generator',{nome: nomepdf, temp: result.temp, versao: tipo})
        .done(function(funfo){
            $.mobile.loading("hide");
            var nomedown = 'http://storage.googleapis.com/mb-fichas-tecnicas/' + nomepdf;
            $('#downloadfile').attr('href', nomedown).attr('download', nomepdf);
            btninvisivel = document.getElementById('downloadfile');
            btninvisivel.click(true);
            console.log(funfo);
            $('#answer').children('div').addClass('alert-success').html('Iniciando download!');
            $('#answer').slideDown().delay(5000).slideUp();
        })
        .fail(function(err){
            if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
                $('#answer').children('div').removeClass('alert-danger');
                $('#answer').children('div').removeClass('alert-success');
            }
            $.mobile.loading("hide");
            $('#answer').children('div').addClass('alert-danger').html('Não é possível reunir os dados no momento! Tente mais tarde.');
            $('#answer').slideDown().delay(5000).slideUp();
        });
    })
    .fail(function(err){
        if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
            $('#answer').children('div').removeClass('alert-danger');
            $('#answer').children('div').removeClass('alert-success');
        }
        var result = JSON.parse(err);
        $.mobile.loading("hide");
        $('#answer').children('div').addClass('alert-danger').html('Não é possível reunir os dados no momento! Tente mais tarde.');
        $('#answer').slideDown().delay(5000).slideUp();
    });
}
</script>