<div class="ui-grid-a">
    <div class="title">
        <h1>Modelos - Ficha Técnica - Transmissão</h1>
        <a onclick="saveft('mod_ft_transmissao');" href="#" class="btn-azul pull-right btn-save"><span class="icon-ok-3"></span>salvar</a>
    </div>
    <div id="answer" class="resposta">
        <div class="alert" role="alert"></div>
    </div>
    <ul id="listcontent" class="content" data-pg-id="<?= $this->pgid; ?>">
        <?php foreach($this->content as $row): ?>
        <li class="row-cont-ficha" id="linha_<?= $row['bmb_nr_linha']; ?>" data-linha="<?= $row['bmb_nr_linha']; ?>">
            <div class="ft-list-row-title">
                <div class="pull-left handlearrasta"><span class="icon-resize-full-alt"></span></div>
                <div class="pull-left mnutipoholder">
                    <?php 
                    $txt = $row['tipo_linha'];
                    switch ($row['tipo_linha']) {
                        case 'cabecalho':
                            $txt = 'Cabeçalho';
                            break;
                        case 'obs':
                            $txt = 'Observação';
                            break;
                        default:
                            $txt = 'Item';
                            break;
                    }
                    ?>
                    <span class="tipo-linha-title"><?= $txt; ?></span> <span class="icon-down-dir"></span>
                    <div class="mnutipo">
                        <div onclick="changetype(this);" class="mnutipo-item">Item</div>
                        <div onclick="changetype(this);" class="mnutipo-item">Cabeçalho</div>
                        <div onclick="changetype(this);" class="mnutipo-item">Observação</div>
                    </div>
                </div>
            </div>
            <div class="not-dragg" style="padding-top: 37px;">
                <table width="100%" border="0" cellspacing="2" cellpadding="0">
                    <tr>
                        <td>
                            <div class="ui-field-contain">
                                <a id="col_<?= $row['bmb_nr_linha']; ?>_0" onclick='opensearch(this);' href="#SelectItem" data-rel="popup" data-idlabel="<?= $row['id_label']; ?>" data-position-to="window" data-transition="pop" class="btn-ficha btn-ficha-label">
                                    &nbsp;<?= ($row['desc_label'] == '0') ? '' : $row['desc_label']; ?>
                                </a>
                            </div>
                        </td>
                        <td class="acoes-col acoes-col-azul">
                            <div class="ui-field-contain">
                                <a href="#" class="pull-left icon-cancel-2 link-icon del-row" data-toggle="tooltip" title="Deletar linha"></a>
                            </div>                                        
                        </td>
                    </tr>
                </table>

                <table data-colunas="<?= $row['qtde_coluna']; ?>" width="100%" border="0" cellspacing="2" cellpadding="0">
                    <tr>
                        <?php for($i = 1; $i <= $row['qtde_coluna']; $i++): ?>
                        <td>
                            <div class="ui-field-contain">
                                <button class="icon-cancel-2 btn-del-col"></button>
                                <a onclick='opensearch(this);' id="col_<?= $row['bmb_nr_linha'] . '_' . $i; ?>" data-vlr="<?php $t = 'id_vlr_' . $i; echo $row[$t]; ?>" data-tipo="<?php $t = 'tipo_vlr_' . $i; echo $row[$t]; ?>" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="btn-ficha">
                                    &nbsp;<?php $t = 'desc_vlr_' . $i; echo ($row[$t] == '0') ? '' : $row[$t]; ?>
                                </a>
                            </div>
                        </td>
                        <?php endfor; ?>
                        <td class="acoes-col">
                            <div class="ui-field-contain">
                                <a onclick="addColumnToDesc(this);" href="#" class="pull-left icon-plus link-icon add-icon" data-toggle="tooltip" title="Adicionar coluna"></a>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </li>
        <?php endforeach; ?> 
    </ul><!-- /content -->

    <a href="#" onclick="addRowToContent();" class="btn-azul pull-right" id="add-row-ficha"><span class="icon-plus"></span>adicionar</a>

</div><!-- ui-grid-a -->

<script src="/js/ft_controller.js"></script>
<script type="text/javascript">
$(document).on('pagehide', 'div', function (event, ui) { 
    var page = jQuery(event.target);
    if (page.attr('data-cache') == 'never') { 
        page.remove(); 
    }; 
});
$('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
$('#mod_ft_transmissao').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");


</script>