application: dev-mb-base
version: v1-0-0 #versao da api.atualizacao da api.correcao de bug
runtime: php
api_version: 1

handlers:
- url: /images
  static_dir: public_html/images

- url: /comparativos
  static_dir: public_html/images/comparativos

- url: /js
  static_dir: public_html/js

- url: /css
  static_dir: public_html/css

- url: /font
  static_dir: public_html/font

- url: /.*
  script: public_html/index.php