application: mb-base
version: v1-4-0 #versao da api - atualizacao da api - correcao de bug
runtime: php55
api_version: 1

handlers:
- url: /images
  static_dir: public_html/images

- url: /comparativos
  static_dir: public_html/images/comparativos

- url: /js
  static_dir: public_html/js

- url: /css
  static_dir: public_html/css

- url: /font
  static_dir: public_html/font

- url: /font_old
  static_dir: public_html/font_old

- url: /.*
  script: public_html/index.php

#env_variables:
#APPLICATION_ENVIROMENT: 'production'