<div class="popup-wrapper">
	<div class="popup">
		<div class="div-form-popup">
			<form class="form-popup" action="/default/recovery" method="post">
				<input type="text" name="emailsend" id="emailsend" placeholder="Informe seu e-mail para recuperar a senha" class="input-login" /><br /><br />
				<input type="submit" value="Recuperar" />
			</form>
		</div>
	</div>
</div>
<div class="popup-overlay"></div>

<div class="wrapper">
	<div class="content">
		<div class="logo">
			<img src="images/logo_login.png" alt="MB Base" />
		</div>
		<div class="div-form">
			<?php if($this->loginfail == 1): ?>
			<div class="alert alert-danger" role="alert">Login ou Senha Errado!</div>
			<?php endif; ?>
			<form action="/default/login" method="post">
				<div class="row">
					<input type="text" name="login" id="login" placeholder="E-mail" class="input-login" />
					<input type="password" name="senha" placeholder="Senha" class="input-login" />
					<input type="submit" value="OK" />
				</div>
				<div class="row esqueci-senha">
					<!-- <a id="passrecover" title="Recuperar senha">Esqueci a senha</a> -->
				</div>
			</form>
		</div>
	</div>
</div>
<!-- <a style="color: #FFFFFF">IP: <?= $this->ip; ?></a> -->
<script type="text/javascript">
	$('#login').focus();
	$('#passrecover').on('click',function(){

	});
	$('.popup-overlay').hide();
	$('.popup-wrapper').hide();
</script>