<div id="analise" class="ui-grid-a">


            <div class="title">

                <div class="holder-search">
                    <input class="search-analise" type="text" name="search-title-analise" value="" data-mini="true" placeholder="&#xe9b8; Busque por um novo termo (Precione a tecla enter para realizar a busca)" style="font-family:fontello, Arial;">
                </div>

                <h1>ANÁLISE DO TERMO</h1>
            </div>
            
            <div class="content">

            <div id="tabs">
                <ul>
                    <li><a href="#tab-geral">Geral</a></li>
                    <li><a href="#tab-modelos">Modelos</a></li>
                </ul>

                <div class="content-tabs" id="tab-geral">

                <!-- TABLE DE MODELOS INDIVIDUAIS -->
                    <table id="agrupamentos" class="modelos-caminhoes">
                    <thead>
                        <tr>
                        <td colspan="2" class="name">Ficha Técnica</td>
                        </tr>
                        <tr>
                            <td>Descrição</td>
                            <td>Itens</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>uhsusdhushduashd sudhasudhasuda suhduhau</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr> 
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>   
                    </tbody>
                    </table>

                    <!-- TABLE DE MODELOS INDIVIDUAIS -->
                    <table id="agrupamentos" class="modelos-caminhoes">
                    <thead>
                        <tr>
                        <td colspan="2" class="name">Comparativos</td>
                        </tr>
                        <tr>
                            <td>Descrição</td>
                            <td>Itens</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr> 
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>   
                    </tbody>
                    </table>

                    <table id="agrupamentos" class="modelos-caminhoes">
                    <thead>
                        <tr>
                        <td colspan="2" class="name">UP</td>
                        </tr>
                        <tr>
                            <td>Descrição</td>
                            <td>Itens</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr> 
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>   
                    </tbody>
                    </table>

                    <table id="agrupamentos" class="modelos-caminhoes">
                    <thead>
                        <tr>
                        <td colspan="2" class="name">Walk Around</td>
                        </tr>
                        <tr>
                            <td>Descrição</td>
                            <td>Itens</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr> 
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                        </tr>   
                    </tbody>
                    </table>


                    <!-- TABLE DE MODELOS INDIVIDUAIS - Analise Geral -->
                    <table id="analise-geral" class="modelos-caminhoes">
                    <thead>
                        <tr>
                            <td>                            
                            <div class="ui-select ui-nodisc-icon">
                                <select onchange="searchpg();" name="select-native-2" id="grupo_pg" data-mini="true" class="ui-nodisc-icon">
                                    <option value="Todos">Visão</option>
                                    <option value="Todos">Ficha Técnica</option>
                                    <option value="Todos">Comparativos</option>
                                </select>
                            </div>
                            </td>
                            <td>
                             <div class="ui-select ui-nodisc-icon">
                                <select onchange="searchpg();" name="select-native-2" id="grupo_pg" data-mini="true" class="ui-nodisc-icon">
                                    <option value="Todos">Agrupamento</option>
                                    <option value="Todos">Geral</option>
                                    <option value="Todos">Dimensões</option>
                                    <option value="Todos">Pesos</option>
                                </select>
                            </div>
                            </td>
                            <td>Descrição Alias</td>
                            <td>Itens</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Ficha Técnica</td>
                            <td>Geral</td>
                            <td>834673467364</td>
                            <td>834673467364</td>
                        </tr>
                        <tr>
                            <td>Comparativos</td>
                            <td>Dimensões</td>
                            <td>834673467364</td>
                            <td>834673467364</td>
                        </tr>
                        <tr>
                            <td>Qt de Concorrentes</td>
                            <td>3</td>
                            <td>834673467364</td>
                            <td>834673467364</td>
                        </tr>
                        <tr>
                            <td>Ficha Técnica</td>
                            <td>Sim</td>
                            <td>834673467364</td>
                            <td>834673467364</td>
                        </tr> 
                        <tr>
                            <td>OEE</td>
                            <td>OI</td>
                            <td>834673467364</td>
                            <td>834673467364</td>
                        </tr>
                    </tbody>
                    </table>


                </div>

                <div class="content-tabs" id="tab-modelos">
                    <div id="filter">
                        <input class="search" placeholder="&#xe9b8; Pesquise por modelo" style="font-family:fontello, Arial;" />

                        <div class="list">
                        <!-- TABLE DE MODELOS INDIVIDUAIS -->
                            <table id="analise-table-modelos" class="modelos-caminhoes">
                            <thead>
                                <tr>
                                <td colspan="2" class="name">805</td>
                                </tr>
                                <tr>
                                    <td>Descrição</td>
                                    <td>Itens</td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Aplicação</td>
                                    <td>834673467364</td>
                                </tr>
                                <tr>
                                    <td>Qt de Fotos</td>
                                    <td>5</td>
                                </tr>
                                <tr>
                                    <td>Qt de Concorrentes</td>
                                    <td>3</td>
                                </tr>
                                <tr>
                                    <td>Ficha Técnica</td>
                                    <td>Sim</td>
                                </tr> 
                                <tr>
                                    <td>OEE</td>
                                    <td>OI</td>
                                </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                            <td colspan="2">
                                <a href="#" class="btn-azul" data-toggle="tooltip" title="Ver mais informações do modelo">(<span class="icon-info-1"></span>) Ver mais</a>
                                </td>
                                </tr>
                            </tfoot>
                            </table>

                            <!-- TABLE DE MODELOS INDIVIDUAIS -->
                            <table id="analise-table-modelos" class="modelos-caminhoes">
                            <thead>
                                <tr>
                                <td colspan="2" class="name">1016</td>
                                </tr>
                                <tr>
                                    <td>Descrição</td>
                                    <td>Itens</td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>OE</td>
                                    <td>OI</td>
                                </tr>
                                <tr>
                                    <td>OE</td>
                                    <td>OI</td>
                                </tr>
                                <tr>
                                    <td>OEE</td>
                                    <td>OI</td>
                                </tr>
                                <tr>
                                    <td>OEE</td>
                                    <td>OI</td>
                                </tr> 
                                <tr>
                                    <td>OEE</td>
                                    <td>OI</td>
                                </tr>   
                            </tbody>
                            <tfoot>
                            <tr>
                            <td colspan="2">
                                <a href="#" class="btn-azul" data-toggle="tooltip" title="Ver mais informações do modelo">(<span class="icon-info-1"></span>) Ver mais</a>
                                </td>
                                </tr>
                            </tfoot>
                                
                            </table>
                        </div><!-- LIST -->
                    </div><!-- LIST -->

                </div><!-- FIM CONTENT-MODELOS -->


            </div><!-- tabs -->


            </div><!-- content -->

        
        </div><!-- ui-grid-a -->

        <script>
        $('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
        $('#mnulateralesquerdo').children('div:first').children('ul').children('li:first').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");
		    var options = {
		      valueNames: [ 'name' ]
		    };

		    var userList = new List('filter', options);

       // $( document ).on( "pageinit", function() {
        //    $("#agrupamentos > tr").click(function() {
        //        $('#analise-geral').removeAttr('display');
                //$("#analise-geral").slideDown('fast').show();
                //$(this).removeClass('aaa').addClass('bbb');
       //     });
      //  });

        $(document).ready(function(){
            $("#agrupamentos > tbody > tr").click(function() {
                //$('#analise-geral').Toggle('fast').collapse('hide');
                $('#analise-geral').css('display', 'table');
            });
        });
		</script>