
<div id="mnulateralesquerdo" data-role="collapsibleset" data-mini="true" data-collapsed-icon="false" class="itens-menu-left">
    <?php foreach($this->menu as $title => $content): ?>
    <div data-role="collapsible" id="collapsible">
        <h3><span class="icon-folder-2"></span><?= $title; ?></h3>
        <ul data-role="listview" data-inset="false" data-icon="false" class="lista">
        <?php foreach($content as $res): ?>
            <li>
                <a data-ajax="false" data-id="<?= $res['id']; ?>" href="/analise/<?= $res['link']; ?>">
                        <?= $res['desc']; ?>
                </a>
            </li>
        <?php endforeach; ?>     
        </ul>
    </div>
    <?php endforeach; ?>
</div>
