<div id="analise" class="ui-grid-a">

    <div class="title">

        <h1>Resumo</h1>

        <a id="gerar-item" class="btn-azul pull-right btn-save ui-link"  href="#SelectItem" style="float:right;"><span class="icon-ok-3"></span>Gerar</a>
    </div>
            
    <div id="resumo-analise" class="content">

        <div id="collapseBlack" data-role="collapsible-set" class="ui-collapsible-set">
            <div data-role="collapsible" data-collapsed="false" class="ui-collapsible ui-collapsible-inset">
                <h3 class="listItemNoIcon">Agrupamento</h3>
                <div class="ui-collapsible-content" aria-hidden="false">
                    <div class="filters-analise">
                        <section class="grid-filtered">

                            <div class="title-checkbox"><h2>Agrupamento</h2></div>

                            <div class="holder-checkbox">
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Ficha Técnica</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Cabina</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Dados</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                     <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Modelos</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                     <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Up</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">I agree</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                            </div>
                        </section><!-- SECTION CARACTERÍSTICA -->

                        <section class="grid-filtered">

                            <div class="title-checkbox"><h2>Modelo</h2></div>

                            <div class="holder-checkbox">
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Accelo</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Cabina</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Dados</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Atego</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Cabina</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Dados</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Actros</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Cabina</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Dados</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Axor</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">2003</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">1746</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">1980</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                                <ul class="briefElements">
                                    <li class="ui-checkbox masterChecked">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">Atron</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">815</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                    <li class="ui-checkbox childCheckBox">
                                        <label for="checkbox-enhanced" class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">1016</label>
                                        <input type="checkbox" name="checkbox-enhanced" id="checkbox-enhanced" data-enhanced="true"  data-theme="b">
                                    </li>
                                </ul>
                            </div>
                        </section> <!-- SECTION MODELO -->
                        <a id="gerar-item" onclick="limpaSelecao();"  class="btn-azul pull-right btn-save ui-link" href="#" style="float:right; margin-top: 13px;"><span class="icon-pencil-2"></span>Limpar</a>
                    </div>
                </div>
            </div>
            <div  id="collapseBlack" data-role="collapsible" data-collapsed="false" class="ui-collapsible ui-collapsible-inset">
                <h3 class="listItemNoIcon">Resultado</h3>
                <div class="ui-collapsible-content" aria-hidden="false">
                I have attribute set manually on my container to set the color to match the content block I'm in. 
                </div>
            </div>
        </div>

    </div><!-- content -->

</div><!-- ui-grid-a -->

<script>
$('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
$('#mnulateralesquerdo').children('div:first').children('ul').children('li:last-child').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");
    var options = {
      valueNames: [ 'name' ]
    };

    var userList = new List('filter', options);

$(document).ready(function(){
    $("#gerar-item").click(function() {
        $(".result-fromfilter").toggle('show');
    });
    $( "#filtros-dropdawn" ).trigger( "collapse" ); 

    //Adiciona a Classe do Checkbox como on se a label for clicada
    $("li.masterChecked > label").click(function() {
        //Encontra a label dentro do <ul> e adiciona a class.
        $(this).parents('ul:eq(0)').find("label").addClass("ui-checkbox-on").removeClass("ui-checkbox-off");
        //Adiciona o data-cacheval = false para deixar ativo o input
        $(this).parents('ul:eq(0)').find("input").attr('data-cacheval', 'false');
    });
    $(".ui-collapsible-heading-toggle").click(function(){
    $( ".ui-collapsible-content" ).trigger( "collapse" );
    });

   
});

/* ----------->>> FUNÇÃO LIMPA CHECKBOX <<<------------*/
function limpaSelecao(){
    $("li.ui-checkbox").each(
        function(){
           $(this).find("label").removeClass("ui-checkbox-on").addClass("ui-checkbox-off");
           $(this).find("input").attr('data-cacheval', 'true');
        }
    );                    
}

</script>