<div id="analise-do-termo" class="ui-grid-a">
    <div class="title">
        <div class="holder-search">
            <input class="search-analise" type="text" name="search-title-analise" value="" data-mini="true" placeholder="Busque por um novo termo (Precione a tecla enter para realizar a busca)" style="font-family:fontello, Arial;">
        </div>
        <h1>ANÁLISE DO TERMO</h1>
    </div>

    <div class="content">
        <div class="content-tabs" id="tab-geral">
            <table id="agrupamentos" class="modelos-caminhoes">
                <thead>
                    <tr>
                        <td colspan="2" class="name">Ficha Técnica</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Content</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr> 
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>   
                </tbody>
            </table>
            <table id="agrupamentos" class="modelos-caminhoes">
                <thead>
                    <tr>
                        <td colspan="2" class="name">Comparativos</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr> 
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>   
                </tbody>
            </table>

            <table id="agrupamentos" class="modelos-caminhoes">
                <thead>
                    <tr>
                        <td colspan="2" class="name">UP</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr> 
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>   
                </tbody>
            </table>

            <table id="agrupamentos" class="modelos-caminhoes">
                <thead>
                    <tr>
                        <td colspan="2" class="name">Walk Around</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr> 
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                    </tr>   
                </tbody>
            </table>


            <table id="analise-geral" class="modelos-caminhoes">
                <thead>
                    <tr>
                        <td>                            
                            <div class="ui-select ui-nodisc-icon">
                                <select onchange="searchpg();" name="select-native-2" id="grupo_pg" data-mini="true" class="ui-nodisc-icon">
                                        <option value="Todos">Modelo</option>
                                    <option value="Todos">Ficha Técnica</option>
                                    <option value="Todos">Comparativos</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="ui-select ui-nodisc-icon">
                                <select onchange="searchpg();" name="select-native-2" id="grupo_pg" data-mini="true" class="ui-nodisc-icon">
                                        <option value="Todos">Visão</option>
                                    <option value="Todos">Geral</option>
                                    <option value="Todos">Dimensões</option>
                                    <option value="Todos">Pesos</option>
                                </select>
                            </div>
                        </td>
                        <td>Agrupamento</td>
                        <td>Itens</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Ficha Técnica</td>
                        <td>Geral</td>
                        <td>834673467364</td>
                        <td>834673467364</td>
                    </tr>
                    <tr>
                        <td>Comparativos</td>
                        <td>Dimensões</td>
                        <td>834673467364</td>
                        <td>834673467364</td>
                    </tr>
                    <tr>
                        <td>Qt de Concorrentes</td>
                        <td>3</td>
                        <td>834673467364</td>
                        <td>834673467364</td>
                    </tr>
                    <tr>
                        <td>Ficha Técnica</td>
                        <td>Sim</td>
                        <td>834673467364</td>
                        <td>834673467364</td>
                    </tr> 
                    <tr>
                        <td>OEE</td>
                        <td>OI</td>
                        <td>834673467364</td>
                        <td>834673467364</td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>

</div>

<script>
$('#mnulateralesquerdo').children('div:first').attr('data-collapsed', 'false');
$('#mnulateralesquerdo').children('div:first').children('ul').children('li:first-child').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");
var options = {
    valueNames: [ 'name' ]
};

var userList = new List('filter', options);

$(document).ready(function(){
    $('.content').css('overflow','auto');
    $("#agrupamentos > tbody > tr").click(function() {
        $('#analise-geral').css('display', 'table');
    });
});
</script>