/*
VERSÃO DE BKP DE 13 DE ABRIL 2015
O DROPDOWN TROCA APENAS CONCORRENTES
 */
<div class="ui-grid-a">
    <div class="title">
        <h1>Modelos - Comparativos - Geral</h1>
        <a href="#" onclick="savecp();" class="btn-azul pull-right btn-save"><span class="icon-ok-3"></span>salvar</a>
    </div>
    <div id="answer" class="resposta">
        <div class="alert" role="alert"></div>
    </div>
    <div class="content">
        <div class="ui-grid-a" id="modelo-content">
            <div class="ui-block-a" id="bloco-mb">
                <div id="mb-cabina" class="ui-grid-a classificacao-bg cabina-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">Cabina</h3>
                    </div>
                    <?php if(isset($this->mbdados['cabina'])){ foreach($this->mbdados['cabina'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /cabina mb -->
                <div id="mb-motor" class="ui-grid-a classificacao-bg motor-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">motor</h3>
                    </div>
                    <?php if(isset($this->mbdados['motor'])){ foreach($this->mbdados['motor'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /motor mb -->
                <div id="mb-cambio" class="ui-grid-a classificacao-bg cambio-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">câmbio</h3>
                    </div>
                    <?php if(isset($this->mbdados['cambio'])){ foreach($this->mbdados['cambio'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /cambio mb -->
                <div id="mb-embreagem" class="ui-grid-a classificacao-bg embreagem-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">embreagem</h3>
                    </div>
                    <?php if(isset($this->mbdados['embreagem'])){ foreach($this->mbdados['embreagem'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /embreagem mb -->
                <div id="mb-eixo-traseiro" class="ui-grid-a classificacao-bg eixo-traseiro-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">eixo traseiro</h3>
                    </div>
                    <?php if(isset($this->mbdados['etraseiro'])){ foreach($this->mbdados['etraseiro'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /eixo traseiro mb -->
                <div id="mb-pneus" class="ui-grid-a classificacao-bg pneus-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">pneus</h3>
                    </div>
                    <?php if(isset($this->mbdados['pneus'])){ foreach($this->mbdados['pneus'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /pneus mb -->
                <div id="mb-freios" class="ui-grid-a classificacao-bg freios-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">freios</h3>
                    </div>
                    <?php if(isset($this->mbdados['freios'])){ foreach($this->mbdados['freios'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /freios mb -->
                <div id="mb-retardador" class="ui-grid-a classificacao-bg retardador-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">retardador</h3>
                    </div>
                    <?php if(isset($this->mbdados['retardador'])){ foreach($this->mbdados['retardador'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /retardador mb -->
                <div id="mb-suspensao-dianteira" class="ui-grid-a classificacao-bg suspensao-dianteira-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">suspensão dianteira</h3>
                    </div>
                    <?php if(isset($this->mbdados['sdianteira'])){ foreach($this->mbdados['sdianteira'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /suspensao dianteira mb -->
                <div id="mb-suspensao-traseira" class="ui-grid-a classificacao-bg suspensao-traseira-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">suspensão traseira</h3>
                    </div>
                    <?php if(isset($this->mbdados['straseira'])){ foreach($this->mbdados['straseira'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /suspensao traseira mb -->
                <div id="mb-chassis" class="ui-grid-a classificacao-bg chassis-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">chassis</h3>
                    </div>
                    <?php if(isset($this->mbdados['chassis'])){ foreach($this->mbdados['chassis'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /chassis mb -->
                <div id="mb-capacidades" class="ui-grid-a classificacao-bg capacidades-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">capacidades</h3>
                    </div>
                    <?php if(isset($this->mbdados['capacidades'])){ foreach($this->mbdados['capacidades'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /capacidades mb -->
                <div id="mb-garantia" class="ui-grid-a classificacao-bg garantia-mb">
                    <div data-role="header">
                        <h3 style="color: #454343;">garantia</h3>
                    </div>
                    <?php if(isset($this->mbdados['garantia'])){ foreach($this->mbdados['garantia'] as $k => $v): ?>
                    <table id="mb_cabina_<?= $k; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                        <tbody>
                            <tr>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[1]; ?></a>
                                </td>
                                <td class="item-class">
                                    <a id="mb_cabina_<?= $k; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $v[0]; ?>" data-tipo="label"><?= $v[2]; ?></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; }?>
                </div><!-- /garantia mb -->
            </div><!-- /bloco-mb -->
            
            <div class="ui-block-b" id="bloco-conc">
                <div id="carousel" class="carousel slide" data-ride="carousel">
                    <div id="controls-slide"><!-- Controls -->
                        <div id="select-conc-button" class="ui-btn ui-corner-all ui-shadow ui-first-child ui-last-child concorrente-selecionado">
                            <div class="">
                                <img src="/images/comparativos/<?= $this->concorrentes[0][1]; ?>" />
                            </div>
                            <div class="myconcorrent" style="text-align: left;">
                                <span><?= $this->concorrentes[0][2]; ?></span>
                            </div>
                        </div>
                        <ul id="mnu-concorrentes" class="pop-dragg">
                            <div class="arrowcp"><span class="icon-up-dir-2"></span></div>
                            <?php foreach($this->concorrentes as $k => $v): ?>
                            <li class="active" data-target="#carousel" data-slide-to="<?= $k; ?>" onclick="changeme(this);" data-img="<?= $v[1]; ?>" data-modelo-id="<?= $v[0]; ?>" data-modelo="<?= $v[2]; ?>">
                                <img src="/images/comparativos/<?= $v[1]; ?>" class="logo-concorrente" align="left" />
                                <p>
                                    <span><?= $v[2]; ?></span>
                                </p>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                        
                    </div><!-- /Controls -->
                
                    <!-- Wrapper for slides -->
                    <div id="concorrenteslist" class="carousel-inner" role="listbox">
                        <?php $ac = 0; foreach($this->modelos as $k => $v): ?>
                        <div class="item<?php if($ac == 0){$ac = 1; echo ' active';} ?>" id="<?= $k; ?>">
                            <div class="carousel-caption">
                                <div class="cp-space" style="height: 42px;"></div>
                                <div id="<?= $k; ?>-cabina" class="ui-grid-a classificacao-bg cabina-conc">
                                    <div data-role="header">
                                        <a onclick="addline('cabina','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['cabina'])){ foreach($v['cabina'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /cabina conc -->
                                <div id="<?= $k; ?>-motor" class="ui-grid-a classificacao-bg motor-conc">
                                    <div data-role="header">
                                        <a onclick="addline('motor','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['motor'])){ foreach($v['motor'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <div>
                                                        <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                    </div>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /motor conc -->
                                
                                <div id="<?= $k; ?>-cambio" class="ui-grid-a classificacao-bg cambio-conc">
                                    <div data-role="header">
                                        <a onclick="addline('cambio','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['cambio'])){ foreach($v['cambio'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /cambio conc -->
                                
                                <div id="<?= $k; ?>-embreagem" class="ui-grid-a classificacao-bg embreagem-conc">
                                    <div data-role="header">
                                        <a onclick="addline('embreagem','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['embreagem'])){ foreach($v['embreagem'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /embreagem conc -->
                                
                                <div id="<?= $k; ?>-eixo-traseiro" class="ui-grid-a classificacao-bg eixo-traseiro-conc">
                                    <div data-role="header">
                                        <a onclick="addline('eixo-traseiro','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right  add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['etraseiro'])){ foreach($v['etraseiro'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /eixo traseiro conc -->
                                
                                <div id="<?= $k; ?>-pneus" class="ui-grid-a classificacao-bg pneus-conc">
                                    <div data-role="header">
                                        <a onclick="addline('pneus','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['pneus'])){ foreach($v['pneus'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /pneus conc -->
                                
                                <div id="<?= $k; ?>-freios" class="ui-grid-a classificacao-bg freios-conc">
                                    <div data-role="header">
                                        <a onclick="addline('freios','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['freios'])){ foreach($v['freios'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /freios conc -->
                                
                                <div id="<?= $k; ?>-retardador" class="ui-grid-a classificacao-bg retardador-conc">
                                    <div data-role="header">
                                        <a onclick="addline('retardador','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['retarder'])){ foreach($v['retarder'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /retardador conc -->
                                
                                <div id="<?= $k; ?>-suspensao-dianteira" class="ui-grid-a classificacao-bg suspensao-dianteira-conc">
                                    <div data-role="header">
                                        <a onclick="addline('suspensao-dianteira','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['sdianteira'])){ foreach($v['sdianteira'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /suspensao dianteira conc -->
                                
                                <div id="<?= $k; ?>-suspensao-traseira" class="ui-grid-a classificacao-bg suspensao-traseira-conc">
                                    <div data-role="header">
                                        <a onclick="addline('suspensao-traseira','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['straseira'])){ foreach($v['straseira'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /suspensao traseira conc -->
                                
                                <div id="<?= $k; ?>-chassis" class="ui-grid-a classificacao-bg chassis-conc">
                                    <div data-role="header">
                                        <a onclick="addline('chassis','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['chassis'])){ foreach($v['chassis'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /chassis conc -->
                                
                                <div id="<?= $k; ?>-capacidades" class="ui-grid-a classificacao-bg capacidades-conc">
                                    <div data-role="header">
                                        <a onclick="addline('capacidades','<?= $k; ?>');" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['capacidades'])){ foreach($v['capacidades'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /capacidades conc -->
                                
                                <div id="<?= $k; ?>-garantia" class="ui-grid-a classificacao-bg garantia-conc">
                                    <div data-role="header">
                                        <a onclick="addline('garantia','<?= $k; ?>');" onclick="" href="#" data-toggle="tooltip" data-placement="left" title="adicionar item" class="ui-btn btn-azul ui-btn-right add-item"><span class="icon-plus"></span>adicionar item</a>
                                    </div>
                                    <?php if(isset($v['garantia'])){ foreach($v['garantia'] as $a => $b): ?>
                                    <table id="cp_cabina_<?= $b[0]; ?>" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">
                                        <tbody>
                                            <tr>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_1" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[3]; ?>" data-tipo="label"><?= $b[3]; ?></a>
                                                </td>
                                                <td class="item-class">
                                                    <a id="mb_cabina_<?= $b[0]; ?>_2" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn" data-vlr="<?= $b[4]; ?>" data-tipo="label"><?= $b[4]; ?></a>
                                                </td>
                                                <td class="icon-class icon-enable"><a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <?php endforeach; }?>
                                </div><!-- /garantia conc -->
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div><!-- /Wrapper for slides -->
                </div><!-- /carousel -->                    
            </div><!-- /bloco-conc -->
        </div>
    </div><!-- /content -->
</div><!-- ui-grid-a -->
<script src="/js/cp_controller.js"></script>
<script id="panel-init">
$(document).on('pagehide', 'div', function (event, ui) { 
    var page = jQuery(event.target);
    if (page.attr('data-cache') == 'never') { 
        page.remove();
    };
});
$('#mnulateralesquerdo').children('div:last').prev().attr('data-collapsed', 'false');
$('#mod_cp_geral').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");


    $(".pop-dragg").hide();
    $("#select-conc-button").mouseenter(function(){
        if($(".pop-dragg").css('display') == 'none'){
            $(".pop-dragg").fadeIn();
        }
    });
    $('#mnu-concorrentes').mouseleave(function(){
        $(".pop-dragg").fadeOut();
    });
    $('#controls-slide').mouseleave(function(){
        if($(".pop-dragg").css('display') == 'block'){
            $(".pop-dragg").fadeOut();
        }
    });
    function addline(tipo,cp){
        var line = '.' + tipo + '-conc';
        var mbln = '#mb-' + tipo;
        var lnid = 'mb_' + tipo + '_';

        var ltln = $(mbln).children('table:last').attr('id');
        if(typeof ltln === 'undefined'){
            ltln = 1;
        }else{
            var x = ltln.split('_');
            var l = x.length - 1;
            ltln = parseInt(x[l]) + 1;
        }
        lnid = lnid + ltln;
        var clid1= lnid + '_1';
        var clid2= lnid + '_2';
        var table= '';
        table += '<table id="' + lnid + '" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">';
        table += '<tr><td class="item-class">';
        table += '<a id="' + clid1 + '" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn">';
        table += '<span class="icon-plus"></span>Item</a>';
        table += '</td><td class="item-class">';
        table += '<a id="' + clid2 + '" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn">';
        table += '<span class="icon-plus"></span>Descritivo MB</a>';
        table += '</td></tr></table>';
        $(mbln).append(table);

        var contador = 0;
        $('#concorrenteslist').children('.item').each(function(){
            contador = contador + 1;
            //substituir o md_ pelo id do concorrente
            var idcp  = $(this).attr('id') + '_' + tipo + '_' + ltln;
            var idcl1 = idcp + '_1';
            var idcl2 = idcp + '_2';
            var idcl3 = idcp + '_3';

            var table1= '';
            table1   += '<table id="' + idcp + '" width="100%" border="0" cellspacing="4" cellpadding="0" class="classificacao">';
            table1   += '<tr><td class="item-class">';
            table1   += '<a id="' + idcl1 + '" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn">';
            table1   += '<span class="icon-plus"></span>Descritivo Concorrente</a>';
            table1   += '</td><td class="item-class">';
            table1   += '<a id="' + idcl2 + '" onclick="opensearch(this);" href="#SelectItem" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn">';
            table1   += '<span class="icon-plus"></span>Argumento de Vendas</a>';
            table1   += '</td>';
            table1   += '<td class="icon-class icon-enable">';
            table1   += '<a onclick="excludeme(this);" href="#" data-toggle="tooltip" title="Excluir item" class="icon-cancel-2 ui-link"></a>';
            table1   += '</td>';
            table1   += '</tr></table>';
            $(this).children('div:first').find(line).append(table1);
        });
    }
    function changeme(obj){
        var img = "/images/comparativos/" + $(obj).attr('data-img');
        var idm = $(obj).attr('data-modelo-id');
        var mod = $(obj).attr('data-modelo');
        $('#select-conc-button').children('div:first').children('img').attr('src',img);
        $('#select-conc-button').children('div:last').children('span').html(mod);
    }
    function excludeme(obj){
        var x = $(obj).closest('table').attr('id').split('_');
        var mb = '#mb_' + x[1] + '_' + x[2];
        $(mb).remove();
        $(obj).closest('table').remove();
        /*
        ESSA PARTE EXCLUI A LINHA DE TODOS OS CONCORRENTES;
        $('#concorrenteslist').children('.item').each(function(){
            var cp = '#' + $(this).attr('id') + '_' + x[1] + '_' + x[2];
            $(cp).remove();
        });*/
    }
    function changemeclass(obj){
        if($(obj).closest('td').hasClass('icon-disable')){
            $(obj).closest('td').removeClass('icon-disable');
            $(obj).closest('td').addClass('icon-enable');
        }
    }
    $('.carousel').carousel({
        pause: true,
        interval: false
    });

    function savecp(){
        loading('show');
        if($('#answer').children('div').hasClass('alert-danger') || $('#answer').children('div').hasClass('alert-success')){
            $('#answer').slideUp('fast');
            $('#answer').children('div').removeClass('alert-danger');
            $('#answer').children('div').removeClass('alert-success');
        }
        var mb = {};
        var ar = ['cabina','motor','cambio','embreagem','eixo-traseiro','pneus','freios','retardador','suspensao-dianteira','suspensao-traseira','chassis','capacidades','garantia'];
        var lt = {};
        mb.cabina     = getItemMB('#mb-cabina',ar[0]);
        mb.motor      = getItemMB('#mb-motor',ar[1]);
        mb.cambio     = getItemMB('#mb-cambio',ar[2]);
        mb.embreagem  = getItemMB('#mb-embreagem',ar[3]);
        mb.eixotx     = getItemMB('#mb-eixo-traseiro',ar[4]);
        mb.pneus      = getItemMB('#mb-pneus',ar[5]);
        mb.freios     = getItemMB('#mb-freios',ar[6]);
        mb.retard     = getItemMB('#mb-retardador',ar[7]);
        mb.sdianteira = getItemMB('#mb-suspensao-dianteira',ar[8]);
        mb.straseira  = getItemMB('#mb-suspensao-traseira',ar[9]);
        mb.chassis    = getItemMB('#mb-chassis',ar[10]);
        mb.capacidade = getItemMB('#mb-capacidades',ar[11]);
        mb.garantia   = getItemMB('#mb-garantia',ar[12]);
        //console.log(mb);
        $('#concorrenteslist').children('.item').each(function(){
            var id  = $(this).attr('id');
            var txt = '#' + id + '-';
            var cp  = {};
            for(i=0;i<ar.length;i++){
                var a = txt + ar[i];
                var b = ar[i];
                cp[b]  = getItemCP(a,b);
            }
            lt[id] = cp;
        });
        $.post('/modelos/actions/savecomparativos',{mercedes: mb, concorrentes: lt})
        .done(function(data){
            console.log(data);
            //var result = JSON.parse(data);
            $.mobile.loading("hide");
            $('#answer').children('div').addClass('alert-success').html('Informações atualizadas com sucesso!');
            $('#answer').slideDown().delay(5000).slideUp();
        }).fail(
            function(err){
            //var result = JSON.parse(err);
            $.mobile.loading("hide");
            $('#answer').children('div').addClass('alert-danger').html('Houve um erro, tente mais tarde!');
            $('#answer').delay(5000).slideDown();
        });
    }
</script>
