<div data-role="popup" id="popWA" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="popup-ficha">
	<a href="#" data-rel="back" data-theme="b" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
	<div data-role="header" data-theme="b" class="header-popup">
		<h3>Conteúdo Walk Around</h3>
	</div>
	<div role="main" class="ui-content content-popup itens-wa">
		<div class="ui-grid-a">
			<div class="ui-block-a">
				<img id="popwaimgshowing" onclick="activenext(this);" src="/images/img-pop-wa.png" width="264px" height="264px" style="cursor: pointer;" />
				<input type="file" style="visibility: hidden;" accept="image/*" id="popwaimg" onchange="getbase64();" />
				<input type="hidden" id="urlaction" value="<?= $this->upload_url; ?>" />
			</div>
			<div class="ui-block-b">
				<a id="popwatitulo" href="#SelectItem" onclick='opensearch(this);' style="margin-bottom: 5px;" data-tipo="0" data-vlr="0" data-rel="popup" data-position-to="window" data-transition="pop" class="wa-pop-titulo">Selecione o título do popup</a>
				<a id="popwadesc" href="#SelectItem" onclick='opensearch(this);' style="height: 250px;" class="wa-pop-desc">Descrição</a>
			</div>                
		</div>
		<div class="traco-b"></div>
		<div class="ui-grid-a">
			<div class="ui-block-a">
				<div id="wapopanswer">
					Enviando arquivo...
				</div>
			</div>
			<div class="ui-block-b">
				<a onclick="gravapopuupinfo();" class="ui-btn btn-azul pull-right" style="width: 100px; height: 15px;">gravar</a>
			</div>
		</div>
	</div> 
</div> 