<div data-role="popup" id="popWAfoto" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="popup-ficha">
    <a href="#" data-rel="back" data-theme="b" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
        
    <div data-role="header" data-theme="b" class="header-popup">
        <h3>Foto Walk Around</h3>
    </div>

    <div role="main" class="ui-content content-popup fotos-wa">

        <div class="ui-grid-a">
            <label for="file">Escolha a imagem:</label>
            <div class="ui-input-text ui-body-inherit ui-corner-all ui-shadow-inset ui-mini">
                <input name="file" id="file" value="" type="file" data-mini="true">
            </div>
        </div>

        <div class="traco-b"></div>

        <div class="ui-grid-a">
            <a href="#" data-rel="back" data-transition="flow" class="ui-btn btn-azul pull-right"><span class="icon-ok-3">&nbsp;</span>Enviar</a>
        </div>

    </div> 

</div> 