<!DOCTYPE html> 
<html>
<head>
    <meta charset="utf-8">
    <title>MBase - Análise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/jquery.mobile.theme-1.4.4.css"/>
    <link rel="stylesheet" href="/css/jquery.mobile-1.4.4.css"/>
    <link rel="stylesheet" href="/css/bootstrap.css"/>
    <link rel="stylesheet" href="/css/select2.min.css"/>
    <link rel="stylesheet" href="/css/default.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="/css/style-modified.css"/>
    <link rel="stylesheet" href="/css/jquery-ui.css" id="jqueryui-style" />
    <link rel="stylesheet" href="/css/fontello.css">
    <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">

    <script src="/js/jquery.js"></script>
    <script src="/js/jquery.mobile-1.4.4.js"></script>
    <script src="/js/bootstrap.js"></script>
    <script src="/js/select2.full.js"></script>
    <script src="/js/jquery-ui.js"></script>
    <script src="/js/list.js"></script>

    <script id="panel-init">
        $( document ).on( "pageinit", "body", function( event ) {
            $( "[data-role='header']" ).toolbar({ theme: "b" });
            $( "[data-role='panel']" ).panel({ theme: "b" });
            $( "[data-role='collapsibleset']" ).collapsibleset({
                theme: "b",
                collapsedIcon: false,
                expandedIcon: false
            });
            $( "[data-role='listview']" ).listview({ theme: "b" });
            $( "[data-role='controlgroup']" ).controlgroup({ theme: "b" });
            $( "[data-role='popup']" ).popup({ theme: "b" });
            $("input[type='radio']").checkboxradio({ theme: "b" });
            $('[data-toggle="tooltip"]').tooltip();
            
            $('input[type="radio"]').click(function(){
                if($(this).attr("value")=="vincular-item-nao"){
                    $(".novo-alias-item-three").hide();
                }
                if($(this).attr("value")=="vincular-item-sim"){
                    $(".novo-alias-item-three").show();
                }
            });
            
            $( "#collapsible .lista .ui-btn" ).click(function() {
                $( "#collapsible .lista .ui-btn" ).css("background","#5f5d5d");
                $(this).css("background","url('/images/arrow-menu-left.png')no-repeat right #525151");
                $('#mnulateralesquerdo').children('div').each(function(){
                    $(this).attr('data-collapsed', 'true');
                });
            });
            
            $(".js-example-basic-multiple").select2();
            
            $(".pop-itens-engenharia").hide();
            $(".add-item-engenharia").click(function() {
                $(".pop-itens-engenharia").fadeIn();
            });
            $(".btn-close").click(function() {
                $(".pop-itens-engenharia").fadeOut();
            });
        });

        /* ---------->>> TABS <<<-----------*/

        $(document).ready(function() {
            $("#tabs").tabs();

            /* ---------->>> DISABLE CSS JQUERY UI FOR MY TABS <<<-----------*/

            $("#tabs").ready(function(){
                $("#jqueryui-style").attr("disabled", "disabled");
            });
        });
    </script>
    
</head>

<body>

    <header data-role="header" data-position="fixed" class="header ui-header-fixed">
        <div class="ui-grid-b">
            <div class="ui-block-a">
                <div class="logo"><img src="/images/logo.jpg"/></div>
            </div>
            <div class="ui-block-b">
                <?php echo $this->action('mnutopo', 'index', 'default') ?>
            </div>
            <div class="ui-block-c">
                <div style="padding-top: 15px;">
                    <ul id="menu-user">
                        <li class="ui-block-a">
                            <a id="mnu-versao-sistema" onclick="mnutoggle(this);" href="#" class="name-user ui-link ui-btn"><?= $this->versaoatual; ?> <span class="icon-down-dir"></span></a>
                            <div id="mnu-open-versao-sistema" class="mnu-sys-version">
                                <ul class="mnu-version">
                                    <?php foreach($this->versoes as $row): ?>
                                    <li data-id="<?= $row[0]; ?>" onclick="changeversionme(this);"><?= $row[1]; ?></li>
                                    <?php endforeach; ?>
                                    <li>Gerenciar Versões</li>
                                </ul>
                            </div>
                        </li>
                        <li class="ui-block-b"><a href="#" class="ui-link ui-btn"><?= $this->usuarionome; ?></a></li>
                        <li class="ui-block-c"><a href="/logout" data-ajax="false" class="icon-logout ui-link ui-btn"></a></li>
                    </ul>
                </div><!-- /navbar -->
            </div>
        </div>
    </header>
    
    <div data-role="panel" data-position-fixed="true" data-display="overlay" data-theme="b" id="add-form" class="ui-panel-open menu-left">
        <?php echo $this->action('mnuesquerdo','index','analise') ?>
    </div><!-- /panel -->    
    
    <div data-role="page" class="page-content">
        <?php echo $this->layout()->content ?>
    </div>
    
    
<!-- POP UP -->
<div data-role="popup" id="SelectItem" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="popup-ficha">
    <a href="#" data-rel="back" data-theme="b" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
    <div data-role="header" data-theme="b" class="header-popup">
    <h1>Resultado do Filtro por Gráfico</h1>
    </div>
    <div role="main" class="ui-content content-popup">
    </div><!-- CONTENT POP UP -->

</div><!-- /POP UP --> 
    
    <!-- POP UP -->
    <div data-role="popup" id="AddAlias" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="popup-ficha">
        <a href="#" onclick="backsearch()" data-theme="b" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
        
        <div data-role="header" data-theme="b" class="header-popup">
            <h3>Adicionar Alias</h3>
        </div>
    
    <div role="main" class="ui-content content-popup add-alias">
        <div class="ui-grid-a row-01">
            <div class="ui-block-a">
                <label>finalidade</label>
                <fieldset class="ui-controlgroup ui-controlgroup-horizontal ui-corner-all" data-role="controlgroup" data-type="horizontal" data-mini="true">
                    <div class="ui-controlgroup-controls">

                        <div class="ui-radio">
                            <label class="ui-btn ui-corner-all ui-btn-inherit ui-radio-off" for="new-alias">Label</label>
                            <input data-cacheval="false" name="label-alias" id="new-alias" value="label" checked="checked" type="radio">
                        </div>
                        <div class="ui-radio">
                            <label class="ui-btn ui-corner-all ui-btn-inherit ui-first-child ui-radio-off" for="new-label">Valor</label>
                            <input data-cacheval="true" name="label-alias" id="new-label" value="valor" type="radio">
                        </div>
                        <input type="hidden" id="param_novo_tipo_finalidade" value="label" />
                        <input type="hidden" id="param_novo_tipo_alias" value="alias" />
                        <input type="hidden" id="param_id_alias" value="0" />
                    </div>
                </fieldset>            
            </div>
            <div class="ui-block-b">
                <label>Descritivo comercial</label>
                <div class="ui-input-text ui-body-inherit ui-corner-all ui-mini ui-shadow-inset">
                    <input id="desc_alias_new" data-mini="true" type="text">
                </div>            
            </div>            
        </div><!-- /row-01 -->
        
        <div class="traco-b"></div>
        
        <div class="ui-grid-a row-02">
            <div id="popengitem" class="pop-itens-engenharia">
                <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right btn-close">Close</a>
                <div data-role="header" class="header-popup"><h3>item / descritivo</h3></div>
                <ul id="list_itens_vinculados" class="itens-descricao"></ul>
            </div>
            <div class="ui-input-btn ui-btn ui-icon-delete ui-btn-icon-notext ui-nodisc-icon" data-toggle="tooltip" data-placement="top" title="deletar item">
                <input onclick="backtonormal(this);" type="button" data-enhanced="true" value="<span class='icon-plus'>&nbsp;</span>adicionar item engenharia">
            </div>        
            <a href="#" id="btn_add_item_vinculado" class="ui-btn add-item-engenharia"><span class="icon-plus">&nbsp;</span>adicionar item engenharia</a>
            <input type="hidden" id="itemvinculado" />
        </div><!-- /row-02 -->
        
        <div class="traco-b"></div>
        
        <div class="ui-grid-a row-03">
            <label>Classificação</label>
            <div class="ui-select">
                <select id="myclassifications" class="js-example-basic-multiple" multiple="multiple"></select>
            </div>
        </div><!-- /row-03 -->
        <div class="traco-b"></div>
        <div class="ui-grid-a">
            <a href="#" onclick="savealias();" data-transition="flow" class="ui-btn btn-azul icon-ok-3 pull-right">gravar</a>
        </div>
    </div>
</div> <!-- /POP UP -->                        
    

    <!-- POP UP -->
    <div data-role="popup" id="DamClassificacao" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="popup-ficha">
        <a href="#" data-rel="back" data-theme="b" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
        
        <div data-role="header" data-theme="b" class="header-popup">
            <h3>Comercial - Classificação</h3>
        </div>
    
        <div role="main" class="ui-content content-popup comercial-classificacao">
            <div class="ui-grid-a row-01">
                <div class="ui-block-a">
                    <label>Versão MB Base</label>
                    <div class="ui-input-text ui-body-inherit ui-corner-all ui-state-disabled ui-shadow-inset">
                        <input disabled="disabled" name="textinput-1" id="textinput-1" placeholder="Texto versão mb base" value="" type="text">
                    </div>                
                </div>
                <div class="ui-block-b">
                    <label>ID Classificação</label>                
                    <div class="ui-input-text ui-body-inherit ui-corner-all ui-state-disabled ui-shadow-inset">
                        <input disabled="disabled" name="textinput-1" id="textinput-1" placeholder="texto id classificação" value="" type="text">
                    </div>                
                </div>                
            </div><!-- /row-01 -->
            
            <div class="traco-b"></div>
            
            <div class="ui-grid-a row-02">
                <div class="ui-block-a">
                    <label>Tipo base</label>
                    <fieldset class="ui-controlgroup ui-controlgroup-horizontal ui-corner-all ui-mini" data-role="controlgroup" data-type="horizontal" data-mini="true">
                        <div class="ui-controlgroup-controls ">
                            <div class="ui-radio ui-mini">
                                <label class="ui-btn ui-corner-all ui-btn-inherit ui-first-child ui-radio-off" for="comercial">Comercial</label>
                                <input data-cacheval="false" name="tipo-base" id="comercial" value="comercial" checked="checked" type="radio">
                            </div>
                            <div class="ui-radio ui-mini">
                                <label class="ui-btn ui-corner-all ui-btn-inherit ui-radio-off" for="tecnica">Técnica</label>
                                <input data-cacheval="true" name="tipo-base" id="tecnica" value="tecnica" type="radio">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="ui-block-b">
                    <label for="select-choice-1" class="select">Agrupamento</label>
                    <div class="ui-select">
                        <div class="ui-btn ui-icon-carat-d ui-btn-icon-right ui-corner-all ui-shadow ui-nodisc-icon" id="agrupamento-button">
                            <span>Escolha uma opção</span>
                            <select name="agrupamento" id="agrupamento">
                                <option value="ficha">Ficha técnica</option>
                                <option value="engenharia">Engenharia</option>
                                <option value="up">UP</option>
                                <option value="comparativos">Comparativos</option>
                                <option value="wa">Walk Around</option>                                
                            </select>
                        </div>
                    </div>
                </div> 
                               
            </div><!-- /row-02 -->
            
            <div class="traco-b"></div>
        
            <div class="ui-grid-a row-03">
                <label>Classificação</label>
                <div class="ui-input-text ui-body-inherit ui-corner-all ui-shadow-inset">
                    <input name="text-basic" id="text-basic" value="" type="text" data-mini="true">
                </div>            
            </div><!-- /row-03 -->
            
            <div class="traco-b"></div>
            
            <div class="ui-grid-a row-04">
                <a href="#" data-rel="back" data-transition="flow" class="ui-btn btn-azul pull-right"><span class="icon-ok-3">&nbsp;</span>gravar</a>
            </div><!-- /row-03 -->
            
        
        </div><!-- /content-popup -->
        
    </div> <!-- /POP UP -->  
    
    
<script id="panel-init">
$('input:radio[name=filtro1]').click(function(){
    $('#param_tipo').val($(this).val());
    search();
});

$('input:radio[name=filtro2]').click(function(){
    $('#param_finalidade').val($(this).val());
    search();
});

function selectme(obj){
    var txt = $(obj).html();
    var cod = $(obj).attr('data-vinculo-id');
    $('#btn_add_item_vinculado').html(txt);
    $('#itemvinculado').val(cod);
    $(".pop-itens-engenharia").fadeOut();
    $('#param_novo_tipo_alias').val('item');
}

function backtonormal(obj){
    $('#btn_add_item_vinculado').html($(obj).val());
    $('#param_novo_tipo_alias').val('alias');
    $('#itemvinculado').val('');
}

function savealias(){
    if(($('#desc_alias_new').val() == '') || ($('#myclassifications').val() == '')){
        alert('Informe a descrição e a Classificação!');
        return;
    }
    var paid = $('#param_id_alias').val();
    var fina = $('#param_novo_tipo_finalidade').val();
    var tipo = $('#param_novo_tipo_alias').val();
    var desc = $('#desc_alias_new').val();
    var vinc = $('#itemvinculado').val();
    var clas = $('#myclassifications').val();
    console.log(clas);
    $.post('/modelos/actions/savealias',{
        param_id_alias : paid,
        param_id_classificacao: clas,
        param_desc_alias:desc,
        param_finalidade:fina,
        param_tipo:tipo,
        param_item_vinculado:vinc,
        param_nivel_item_vinculado: 'modelo'
    },function(data){
        console.log(data);
        $("input[name='label-alias']:first").prev().click();
        $("input[name='label-alias']").checkboxradio("refresh");
        $('#param_id_alias').val('0');
        $('#param_alias_finalidade').val('valor');
        $('#param_tipo_alias').val('alias');
        $('#desc_alias_new').val('');
        $('#itemvinculado').val('');
        $('#myclassifications').select2("val", "");
        $('#btn_add_item_vinculado').html('<span class="icon-plus">&nbsp;</span>adicionar item engenharia');
        searchpg();
        backsearch();
    });
}

function showalias(up,obj){
    if(typeof up === "undefined"){
        $('#SelectItem').popup('close');
        setTimeout(function(){$('#AddAlias').popup('open');},500);
    }else{
        var x = up;
        if(up == 0){
            y = $(obj).closest('tr').attr('id');
            y = y.split('_');
            x = y[2];
            console.log[y];
        }
        $.post('/modelos/index/getaliasdata', {id: x}, function(data){
            var ret = JSON.parse(data);
            console.log(ret);
            $('#desc_alias_new').val(ret.desc_alias);
            $('#myclassifications').select2("val", ret.id_classificacao);
            if(up != 0)
                $('#param_id_alias').val(up);
            if((ret.cod_item_vinculado !== null) && (ret.desc_item_vinculado !== null)){
                console.log('entrando aqui');
                $('#param_alias_finalidade').val('item');
                $('#btn_add_item_vinculado').html(ret.desc_item_vinculado);
                $('#itemvinculado').val(ret.cod_item_vinculado);
                $("input[name='label-alias']:last").prev().click();
                $("input[name='label-alias']").checkboxradio("refresh");
                $('#param_tipo_alias').val('item');
            }
            $('#SelectItem').popup('close');
            setTimeout(function(){$('#AddAlias').popup('open');},500);
        });
    }
}

function backsearch(){
    $('#AddAlias').popup('close');
    $("input[name='label-alias']:first").prev().click();
    $("input[name='label-alias']").checkboxradio("refresh");
    $('#param_id_alias').val('0');
    $('#param_alias_finalidade').val('valor');
    $('#param_tipo_alias').val('alias');
    $('#desc_alias_new').val('');
    $('#itemvinculado').val('');
    $('#myclassifications').select2("val", "");
    $('#btn_add_item_vinculado').html('<span class="icon-plus">&nbsp;</span>adicionar item engenharia');
    //setTimeout(function(){$('#SelectItem').popup('open');},500);
}

$.post('/modelos/index/loadclassificacao',function(resposta){
    var options = JSON.parse(resposta);
    for(i=0;i<options.length;i++){
        var opt = '<option value="' + options[i].id_classificacao + '">' + options[i].desc_classificacao + '</option>';
        $('#myclassifications').append(opt);
    }
});
$.post('/modelos/index/loaditemengenharia',function(resposta){
    var options = JSON.parse(resposta);
    for(i=0;i<options.length;i++){
        var opt = '<li onclick="selectme(this);" data-vinculo-id="' + options[i].cod_item + '">' + options[i].item_desc + '</li>';
        $('#list_itens_vinculados').append(opt);
    }
});
/**
 * Função que exibe e oculta o menu de versão
 * Criado por: Eliel Fernandes
 * Criado em: 14/08/2015
 * Versão: 1.0.0
 */
function mnutoggle(obj){
    $('#mnu-open-versao-sistema').stop().fadeToggle('fast');
}

/**
 * Função que troca a versão do sistema
 * Criado por: Eliel Fernandes
 * Criado em: 14/08/2015
 * Versão: 1.0.0
 */
function changeversionme(obj){
    versao = $(obj).html() + '<span class="icon-down-dir"></span>';
    idnva  = $(obj).attr('data-id');
    $.post('/index/changeversion',{id: idnva})
    .done(function(data){
        $('#mnu-versao-sistema').html(versao);
        $('#mnu-open-versao-sistema').stop().fadeToggle('fast');
        location.reload(true);
    });
}
</script>
</body>
</html>