<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>MB BASE - Sistema Administrativo</title>
	<meta name="robots" content="noindex, follow">
	<meta name="robots" content="index, nofollow">
	<meta name="robots" content="noindex, nofollow">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="shortcut icon" href="/images/favicon.ico">
	<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">

	<link rel="stylesheet" href="/css/jquery.mobile.theme-1.4.4.css"/>
	<link rel="stylesheet" href="/css/jquery.mobile-1.4.4.css"/>
	<link rel="stylesheet" href="/css/bootstrap.css"/>
	<link rel="stylesheet" href="/css/default.css"/>
	<link rel="stylesheet" href="/css/style.css"/>
	<link rel="stylesheet" href="css/login.css" />

    <script src="js/jquery.js"></script>
    <script>
    	var obj = document.getElementById('hhead');
    	console.log(obj);
    </script>
</head>

<body>
	<?php echo $this->layout()->content ?>
</body>
</html>