<!DOCTYPE html> 
<html>
<head>
	<meta charset="utf-8">
    <title>MBase - Modelos Comercial</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="/css/jquery.mobile.theme-1.4.4.css"/>
	<link rel="stylesheet" href="/css/jquery.mobile-1.4.4.css"/>
    <link rel="stylesheet" href="/css/carrousel.css"/>
	<link rel="stylesheet" href="/css/bootstrap.css"/>
    <link rel="stylesheet" href="/css/select2.min.css"/>
	<link rel="stylesheet" href="/css/default.css"/>
	<link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="/css/style-modified.css"/>
	<link rel="stylesheet" href="/css/jquery-ui.css" id="jqueryui-style" />
    <link rel="stylesheet" href="/css/fontello.css" />
    <link rel="stylesheet" href="/css/fontello_old.css" />
    <link rel="stylesheet" href="/css/jQMProgressBar.css" />
    <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
    
	<script src="/js/jquery.js"></script>
    <script src="/js/jquery.mobile-1.4.4.js"></script>
	<script src="/js/bootstrap.js"></script>
    <script src="/js/touch-dnd.js"></script>
    <script src="/js/select2.full.js"></script>
	<script src="/js/jquery-ui.js"></script>
    <script src="/js/jquery.infinitescroll.js"></script>
    <script src="/js/modelos_ctrl.js"></script>
    <script src="/js/jQMProgressBar.js"></script>

	<script id="panel-init">
		$(document).on("pageinit", "body", function(event){
			$( "[data-role='header']" ).toolbar({ theme: "b" });
			$( "[data-role='panel']" ).panel({ theme: "b" });
			$( "[data-role='collapsibleset']" ).collapsibleset({
                theme: "b",
                collapsedIcon: false, 
                expandedIcon: false
            });
			$( "[data-role='listview']" ).listview({ theme: "b" });
			$( "[data-role='controlgroup']" ).controlgroup({ theme: "b" });
			$( "[data-role='popup']" ).popup({ theme: "b" });
			$("input[type='radio']").checkboxradio({ theme: "b" });
			$('[data-toggle="tooltip"]').tooltip();
			
			$('input[type="radio"]').click(function(){
				if($(this).attr("value")=="vincular-item-nao"){
					$(".novo-alias-item-three").hide();
				}
				if($(this).attr("value")=="vincular-item-sim"){
					$(".novo-alias-item-three").show();
				}
			});
			
			$( "#collapsible .lista .ui-btn" ).click(function() {
				$( "#collapsible .lista .ui-btn" ).css("background","#5f5d5d");
				$(this).css("background","url('/images/arrow-menu-left.png')no-repeat right");
                $('#mnulateralesquerdo').children('div').each(function(){
                    $(this).attr('data-collapsed', 'true');
                });
			});
			$(".js-example-basic-multiple").select2();
            $(".pop-itens-engenharia").hide();
            $(".add-item-engenharia").click(function() {
                $(".pop-itens-engenharia").fadeIn();
            });
            $(".btn-close").click(function() {
                $(".pop-itens-engenharia").fadeOut();
            });
		});
        $("#meumodelo").select2();

        /* ---------->>> TABS <<<-----------*/
        $(document).on('pageshow', 'div', function (event, ui) {
            /*Abre as tabs assim que a página carrega*/
            $("#tabs").tabs();

            /* ---------->>> DISABLE CSS JQUERY UI FOR MY TABS <<<-----------*/
            $("#tabs").ready(function(){
                $("#jqueryui-style").attr("disabled", "disabled");
            });

        });
	</script>
    
</head>

<body>

    <header data-role="header" data-position="fixed" class="header">
        <div class="ui-grid-b">
        	<div class="ui-block-a">
            	<div class="logo"><img src="/images/logo.jpg"/></div>
            </div>
            <div class="ui-block-b">
                <?php echo $this->action('mnutopo', 'index', 'default') ?>
            </div>
            <div class="ui-block-c">
                <div style="padding-top: 15px;">
                    <ul id="menu-user">
                        <li class="ui-block-a">
                            <a id="mnu-versao-sistema" onclick="mnutoggle(this);" href="#" class="name-user ui-link ui-btn"><?= $this->versaoatual; ?> <span class="icon-down-dir"></span></a>
                            <div id="mnu-open-versao-sistema" class="mnu-sys-version">
                                <ul class="mnu-version">
                                    <?php foreach($this->versoes as $row): ?>
                                    <li data-id="<?= $row[0]; ?>" onclick="changeversionme(this);"><?= $row[1]; ?></li>
                                    <?php endforeach; ?>
                                    <li>Gerenciar Versões</li>
                                </ul>
                            </div>
                        </li>
                        <li class="ui-block-b"><a href="#" class="ui-link ui-btn"><?= $this->usuarionome; ?></a></li>
                        <li class="ui-block-c"><a href="/logout" data-ajax="false" class="icon-logout ui-link ui-btn"></a></li>
                    </ul>
                </div><!-- /navbar -->
            </div>
        </div>
    </header>
    
    <div data-role="panel" data-position-fixed="true" data-display="overlay" data-theme="b" id="add-form" class="ui-panel-open menu-left">
        <?php echo $this->action('selectfamiliamodelonovo','index','modelos') ?>
        <div class="menu-height">
            <div id="mnulateralesquerdo" data-role="collapsibleset" data-mini="true" data-collapsed-icon="false" class="itens-menu-left">
            	<?php echo $this->action('mnuesquerdo', 'index', 'default') ?>
            </div>
        </div>
    </div><!-- /panel -->    
    
    <div id="pgconteudo" data-role="page" class="page-content" data-cache="never">
        <?php echo $this->layout()->content ?>
    </div>
    
    <?php echo $this->action('buscaealias', 'popups', 'default') ?>
    
    <?php echo $this->action('upconteudo', 'popups', 'default') ?>

    <?php echo $this->action('waconteudo', 'popups', 'default') ?>
    
    <?php echo $this->action('wafoto', 'popups', 'default') ?>

<script id="panel-init">

$(document).ready(function(){

    //Simula o check e descheck das lists (popup > detalhes)
    $('.childCheckbox > label').click(function(){

        if($(this).hasClass("ui-checkbox-off")){
            // first click
            $(this).addClass("ui-checkbox-on").removeClass("ui-checkbox-off");

        }else if($(this).hasClass("ui-checkbox-on")){
            // second clik
            $(this).addClass("ui-checkbox-off").removeClass("ui-checkbox-on");
        }
    });

    //Adiciona a Classe do Checkbox como on se a label for clicada
    $("li.masterChecked > label").click(function() {

        if($(this).hasClass("ui-checkbox-off")){
            // first click
            $(this).addClass("ui-checkbox-on").removeClass("ui-checkbox-off");
            $(this).parents('ul:eq(0)').find("label").addClass("ui-checkbox-on").removeClass("ui-checkbox-off");

        }else if($(this).hasClass("ui-checkbox-on")){
            // second clik
            $(this).addClass("ui-checkbox-off").removeClass("ui-checkbox-on");
            //Encontra as labels dentro do <ul> e adiciona a class.
            $(this).parents('ul:eq(0)').find("label").addClass("ui-checkbox-off").removeClass("ui-checkbox-on");
        }
    });
});

$('input:radio[name=filtro1]').click(function(){
    $('#param_tipo').val($(this).val());
    search();
});
$('input:radio[name=filtro2]').click(function(){
    $('#param_finalidade').val($(this).val());
    search();
});
$('input:radio[name=label-alias]').click(function(){
    $('#param_novo_tipo_finalidade').val($(this).val());
});

$('#SelectItem').popup({
    afteropen: function(e){
        $('body').css('overflow','hidden');
    },
    afterclose: function(e){
        $('body').css('overflow','auto');
    }
});

var vezes = 0;
function clearbeforeme(obj){
    var referencia = $(obj).closest('.select2').prev().attr('id');
    if(referencia == 'myclassifications'){
        console.log('saindo do clear');
        return;
    }
    vezes = vezes + 1;
    if(vezes > 4){
        vezes = 1;
    }
    if(referencia == 'meumodelo' && vezes == 1){
        var text = $("#meumodelo option:selected").text();
        var id   = $('#meumodelo').val();
        if(text != ''){
            $(obj).attr('data-anterior', text);
            $(obj).attr('data-id-anterior', text);
        }
        //console.log('No focus ' + $(obj).attr('data-anterior'));
        $(obj).parent().prev().remove();
        $('#meumodelo').children("option:selected").removeAttr('selected');
    }
}
function verificame(obj){
    var referencia = $(obj).closest('.select2').prev().attr('id');
    if(referencia == 'myclassifications'){
        console.log('saindo');
        return;
    }
    if($('#meumodelo').next().hasClass('select2-container--open')){
        //console.log('tem a classe');
        /*var ua = window.navigator.userAgent;
        var msie = ua.indexOf("MSIE ");
        if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)){
            vezes = 0;
        }*/
    }else{
        var text  = $("#meumodelo option:selected").text();
        //console.log('No blur ' + $(obj).attr('data-anterior'));
        if(text == ''){
            text = $(obj).attr('data-anterior');
        }
        var item  = '<li class="select2-selection__choice" title="' + text + '"><span class="select2-selection__choice__remove" role="presentation">×</span>' + text + '</li>';
        $(obj).closest('ul').prepend(item);
        vezes = 0;
    }
}

/**
 * Função que exibe e oculta o menu de versão
 * Criado por: Eliel Fernandes
 * Criado em: 14/08/2015
 * Versão: 1.0.0
 */
function mnutoggle(obj){
    $('#mnu-open-versao-sistema').stop().fadeToggle('fast');
}

/**
 * Função que troca a versão do sistema
 * Criado por: Eliel Fernandes
 * Criado em: 14/08/2015
 * Versão: 1.0.0
 */
function changeversionme(obj){
    versao = $(obj).html() + '<span class="icon-down-dir"></span>';
    idnva  = $(obj).attr('data-id');
    $.post('/index/changeversion',{id: idnva})
    .done(function(data){
        $('#mnu-versao-sistema').html(versao);
        $('#mnu-open-versao-sistema').stop().fadeToggle('fast');
        location.reload(true);
    });
}



/*$('#mnu-versao-sistema').hover(function(){
    $('#mnu-open-versao-sistema').stop().fadeIn('fast');
},function(){
    //$('#mnu-open-versao-sistema').stop().fadeOut('fast');
});
$('#mnu-list-sys-version').mouseout(function(){
    $('#mnu-open-versao-sistema').stop().fadeOut('fast');
});*/

</script>

</body>
</html>