<div class="ui-grid-a">
	<div class="content">
		<div>
			<div style="color:#ddd; text-shadow:none!important; padding: 50px 10px; font-family: roboto;  margin: 0 auto; width: 525px; line-height: 1.3em; font-size: 40px; font-weight:900; text-align: center;">
            <div style="width:100%;">
                <img src="/images/construcao.png" style="padding: 0px 151px 18px;" />
            </div>
            PÁGINA
            <br />
            <span style="color:#F8BF18">EM CONSTRUÇÃO</span></div>
        </div>
		</div>
	</div>
</div>
<script id="panel-init">
$('#mnulateralesquerdo').children('div:last').attr('data-collapsed', 'false');
$('#mnulateralesquerdo').children('div:last').children('ul').children('li:first').children('a').css("background","url('/images/arrow-menu-left.png')no-repeat right");
</script>